### ISSUE TITLE
Fix functional bugs into the application

### ISSUE THREAD

**Issue by pierregaimard** [pierregaimard/projet08#10]
> Time estimate: 6 hours
> Time spent: 6 hours

### Tests

- [x] Navbar title link should redirect to the homepage
- [x] Done tasks list link should redirect to a done tasks list page
- [x] ToDo tasks list should only display tasks with isDone property set to false
- [x] Done tasks list should only display tasks with isDone property set to true
- [x] Check 'add task' successful message
- [x] Check 'delete task' successful message
- [x] Check 'task done' successful message
- [x] Check 'task undone' successful message
- [x] Check 'user add' successful message
- [x] Check 'user update' successful message

### Todo

- [x] Add link to navbar title
- [x] Add new application page with done tasks list
- [x] Add the link to this page
- [x] Add filter to Todo tasks list to only display toDo tasks
- [x] Fix 'add task' successful message
- [x] Fix 'task undone' successful message
- [x] Clean design (buttons positions, margins, ...)
