### ISSUE TITLE
Customize error pages

### ISSUE THREAD

**Issue by pierregaimard** [pierregaimard/projet08#24]
> Time estimate: 1 hour
> Time spent: 1 hour

### Todo

- [x] Add 404 Error page
- [x] Add 403 Error page
- [x] Add error page for all other errors

### Tests

- [x] non-existent page should return a 404 response status code
- [x] access to unauthorized page should return a 403 response status code
