### ISSUE TITLE
Improve login feature using guard authenticator process

### ISSUE THREAD

**Issue by pierregaimard** [pierregaimard/projet08#4]
> Time estimate: 3 hours
> Time spent: 3 hours

### Tests

- [x] A security token is present in the login form
- [x] Bad credentials infos should return a bad credentials message
- [x] Authentication success should redirect the user to the homepage and security user should be set
- [x] A non authenticated user should not have access to the application pages except /login

### Todo

- [x] Add guard authenticator
- [x] Refactor SecurityController using it
- [x] Refactor Security login form using csrf token
- [x] Add redirection to the home page on authentication success
