### ISSUE TITLE
Improve users management feature

### ISSUE THREAD

**Issue by pierregaimard** [pierregaimard/projet08#7]
> Time estimate: 6 hours
> Time spent: 6 hours

### Tests

- [x] users with role 'ROLE_USER' should not be able to access to **users** section
- [x] users that are not authenticated should not be able to access to **users** section
- [x] 'View users list' button should not be visible if the user is authenticated and has role 'ROLE_USER'
- [x] 'View users list' button should be visible if the user is authenticated and has role 'ROLE_ADMIN'
- [x] add a user information that do not respect the validation constraints should  return an error in 'add_user' & 'edit_user' forms

### Todo

- [x] Remove 'add user' button from base template
- [x] Add a 'View users list' button
- [x] Add role admin condition to 'View users list' button
- [x] Enable entities constraints validation for 'add_user' & 'edit_user' forms
- [x] Add access rule to the firewall
- [x] Add a 'delete' button to users items in users list
