### ISSUE TITLE
Bug fix in tasks management feature

### ISSUE THREAD

**Issue by pierregaimard** [pierregaimard/projet08#8]
> Time estimate: 3 hours
> Time spent: 3 hours

### Tests

- [x] A task should always have a owner property
- [x] When adding a task, the authenticated user should be set as the owner
- [x] The task owner do not change when updating the task
- [x] A task that has no owner should return "anonymous" when calling getOwner function.

### Todo

- [x] Add owner property to Task entity
- [x] return "anonymous" when a task has no owner in getOwner method.
- [x] Add authenticated user as owner on task persist using doctrine event
- [x] Add an 'update' button to tasks
