### ISSUE TITLE
Add new features to tasks management

### ISSUE THREAD

**Issue by pierregaimard** [pierregaimard/projet08#9]
> Time estimate: 3 hours
> Time spent: 4 hours

### Tests

- [x] A task can be deleted if authenticated user is the owner
- [x] A task can't be deleted if authenticated user is not the owner
- [x] A task with "anonymous" owner can be deleted by a user with a role 'ROLE_ADMIN'
- [x] A task with "anonymous" owner can't be deleted by a user with a role 'ROLE_USER'

### Todo

- [x] Add a 'TASK_DELETE' voter to manage task delete
